### ISSUE TITLE
download keeps failing

### ISSUE THREAD

**Issue by WilliamCTurner** [shadoxxhd/steamworkshopdownloader#15]

**Comment by BJRironside** [comment]
confirmo sigue fallando la descarga

**Comment by HADR1AN1** [comment]
I am also suffering the same thing, my downloads are always getting "Timeout". I've read the instructions but to no avail.
![sda](https://user-images.githubusercontent.com/108221432/175812713-bd99c680-0a63-48f6-9ebe-ffa140264641.PNG)

**Comment by shadoxxhd** [comment]
Please post the content of the right text box after a fail.

**Comment by BJRironside** [comment]
![error steamcmd1](https://user-images.githubusercontent.com/108193075/175830009-be378d97-6b53-4aab-a2c8-dff759cd8434.jpg)

**Comment by shadoxxhd** [comment]
> ![error steamcmd1](https://user-images.githubusercontent.com/108193075/175830009-be378d97-6b53-4aab-a2c8-dff759cd8434.jpg)

Cities: Skylines doesn't support anonymous downloads. You need to use a steam account owning the game to download those workshop items.

**Comment by BJRironside** [comment]
![error steamcmd2](https://user-images.githubusercontent.com/108193075/175847672-7eaecbe3-66b5-4250-9d08-3b0797c15032.jpg)

**Comment by BJRironside** [comment]
Ahora mi duda es la siguiente cuando intente esto en SteamCMD, me solicitaba la llave con la que aurizo el acceso a SteamCMD sera que esto provoca el error?

**Comment by shadoxxhd** [comment]
> I tried it in several ways, with or without a user, without a user it throws me an error and with a user it stays that way for hours. (translated)

The error without user is to be expected, since Cities:Skylines requires an account. For the problem with an account, you apparently already found the issue:

> Now my question is the following when I tried this in SteamCMD, it asked me for the key with which I authorize access to SteamCMD, will this cause the error? (translated)

Yes. When using an account for the first time, and the account has SteamGuard active, you need to manually launch steamcmd.exe, enter "login <username>", and then enter password and SteamGuard code when it asks you for it. Once that is done, everything should be working.

I should probably add an explanation of the process to the readme file...
