### ISSUE TITLE
Invalid password issue

### ISSUE THREAD

**Issue by weeewo** [shadoxxhd/steamworkshopdownloader#46]
Password is always invalid in steamcmd, no matter what I do. It's already been set in config and I've done it many times. What am I doing wrong/forgetting to do?

**Comment by shadoxxhd** [comment]
Are you using 2FA? If so, what type of authenticator (mail, code generator)?

**Comment by josefhannes77** [comment]
I have the same issue, is it because I have steam guard on?

**Comment by shadoxxhd** [comment]
> I have the same issue, is it because I have steam guard on?

What type of authenticator are you using, and what's the precise error message?

**Comment by josefhannes77** [comment]
I'm sorry I don't fully understand your question but I'll try, I get an email of a temporary code I need to use to log in to steam, the error message comes when I try to steamcmd to log in to my account I write the code login <user login> and then it ask for the password for the steam account I wrote it down and it gives me an error message saying failed (incorrect password) I have even tried to change password still the same message.

**Comment by shadoxxhd** [comment]
Your previous comment didn't really make it clear where the issue is.
If you want to download items with your steam account while mail-based steam guard is active, you need to follow the instructions here: https://github.com/shadoxxhd/steamworkshopdownloader#non-anonymous-downloads
App-based steam guard currently isn't supported.

**Comment by shadoxxhd** [comment]
Now app based steam guard is supported.
