### ISSUE TITLE
Moving [addon id] done

### ISSUE THREAD

**Issue by RealMrCactus** [shadoxxhd/steamworkshopdownloader#52]
Where does it go??????

```Steam Console Client (c) Valve Corporation - version 1709846822

Loading Steam API...OK



Connecting anonymously to Steam Public...OK

Waiting for client config...OK

Waiting for user info...OK

Downloading item 2551225702 ...

Success. Downloaded item 2551225702 to "C:\Users\bhrae\Downloads\steamcmd\steamapps\workshop\content\294100\2551225702" (1356385 bytes) 
Moving 2551225702 ... DONE
```

i figured it would be in the yknow downloads folder it says it is but its not so im guessing it moved it somewhere and its not in my steam lib path

**Comment by shadoxxhd** [comment]
In version 0.6, the default configuration is to move mods to a `mods/<appid>` directory next to `downloader.exe`.
To revert back to the previous default behavior (downloads to `steamcmd/steamapps/workshop/content/<appid>`), remove the `defaultpath = mods` line from `downloader.ini` (in the same directory as `downloader.exe`).
You can also choose a different `defaultpath`, though with this option you'll always have <appid> subdirectories.
To set a destination directory that doesn't end in <appid>, you need to specify a path for that appid by adding the following lines to the end of `downloader.ini`:
```
[<appid>]
path = <path>
```
With <appid> and <path> replaced with the ID of the app (the number in the steam store URL of the game) and the intended destination, respectively.

The general intention is that you move downloader.exe to its own directory before using it, instead of executing directly from your downloads folder. Doing the latter shouldn't cause issues, but can make it harder to find the downloads and .ini file.

When I added changed the default output path in 0.6, I forgot about steamcmd printing the temporary path - I guess I should add some indicator where the files are moved in the next release...

**Comment by shadoxxhd** [comment]
I updated the README, and the experimental version (v0.7) now prints out where each mod is moved.
