### ISSUE TITLE
Not responding after successful download

### ISSUE THREAD

**Issue by amymor** [shadoxxhd/steamworkshopdownloader#59]
![0078](https://github.com/user-attachments/assets/960ae6cb-7240-4fad-a0d7-b08b25aa4b80)
Versions that have this problem:
[v0.7.1 Experimental](https://github.com/shadoxxhd/steamworkshopdownloader/releases/tag/v0.7.1-alpha)
[v0.7 Experimental](https://github.com/shadoxxhd/steamworkshopdownloader/releases/tag/v0.7-alpha)
The version that has no problem:
[v0.6.0 - Steam Guard compatibility](https://github.com/shadoxxhd/steamworkshopdownloader/releases/tag/v0.6.0)

**Comment by shadoxxhd** [comment]
This issue is caused by a bug in the pywinpty library (andfoy/pywinpty#423); I could replace the pty interface with the old, less responsive method temporarily, but since I wanted to implement eg. a download progress bar in the future, I'll have to use the pty method eventually anyway.
Though perhaps I can find a way to work around the issue...

**Comment by shadoxxhd** [comment]
Workaround implemented in latest release.
