### ISSUE TITLE
Recommend a good Steam Workshop Downloader

### ISSUE THREAD

**Issue by hongjiang11** [shadoxxhd/steamworkshopdownloader#68]
Recommend a good [Steam Workshop Downloader](https://www.steamworkshopdownloader.cc/)
https://www.steamworkshopdownloader.cc/

**Comment by shadoxxhd** [comment]
I'm curious how long they stay online - their predecessor (.io) going down was the inspiration for this project.

But apart from that, it doesn't seem to have any relevance for this project, since I target a different niche (efficient download of workshop items and collections directly from steam via a local application, that can't "go down" if someone forgets to pay for their web server).

**Comment by shadoxxhd** [comment]
Oh, and that website seems to be unable to download collections, and anything that might require an account with steamcmd.

So unless you are strongly opposed to installing an open source application on your PC (but somehow completely fine with using mods downloaded from an untrusted source), that website is strictly inferior to this project.
